// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char DEVICE_LOGIN_NAME[] = "COLOQUE_AQUI_SEU_DEVICE_LOGIN_NAME";
const char SSID[]              = "SEU_SSID";
const char PASS[]              = "SUA_SENHA_WIFI";
const char DEVICE_KEY[]        = "SUA_DEVICE_KEY";


void onCorLedChange();
void onEstadoLedChange();
void onEstadoTempLdrChange();

String corLed;
float temperatura;
int luminosidade;
bool estadoLed;
bool estadoTempLdr;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(corLed, READWRITE, ON_CHANGE, onCorLedChange);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(luminosidade, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(estadoLed, READWRITE, ON_CHANGE, onEstadoLedChange);
  ArduinoCloud.addProperty(estadoTempLdr, READWRITE, ON_CHANGE, onEstadoTempLdrChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
